#!/usr/bin/env python3
"""Export OpenAPI and derive dependency-free TypeScript schema aliases."""

from __future__ import annotations

import json
import os
import sys
import tempfile
from pathlib import Path
from typing import Any

if sys.version_info < (3, 11):  # noqa: UP036 - bootstrap the project's Python
    project_python = Path(__file__).resolve().parents[1] / ".venv/bin/python"
    if project_python.exists():
        os.execv(project_python, [str(project_python), *sys.argv])  # noqa: S606


def ts_type(schema: dict[str, Any], indent: int = 0) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(json.dumps(value, ensure_ascii=False) for value in schema["enum"])
    for union_key in ("anyOf", "oneOf"):
        if union_key in schema:
            return " | ".join(ts_type(item, indent) for item in schema[union_key])
    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(ts_type({**schema, "type": item}, indent) for item in kind)
    if kind == "null":
        return "null"
    if kind == "string":
        return "string"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "array":
        return f"Array<{ts_type(schema.get('items', {}), indent)}>"
    if kind == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        if properties:
            required = set(schema.get("required", []))
            padding = "  " * (indent + 1)
            lines = ["{"]
            for name, value in properties.items():
                optional = "" if name in required else "?"
                lines.append(f"{padding}{json.dumps(name)}{optional}: {ts_type(value, indent + 1)}")
            lines.append("  " * indent + "}")
            return "\n".join(lines)
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {ts_type(additional, indent)}>"
        return "Record<string, unknown>"
    return "unknown"


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    with tempfile.TemporaryDirectory(prefix="onionpi-openapi-") as data_dir:
        os.environ.update(
            {
                "ONIONPI_DATA_DIR": data_dir,
                "ONIONPI_SHARED_DIR": f"{data_dir}/shared",
                "ONIONPI_DB_PATH": f"{data_dir}/openapi.db",
                "ONIONPI_SESSION_SECRET": "openapi-generation-only",
                "ONIONPI_DEMO_MODE": "1",
            }
        )
        sys.path.insert(0, str(root / "backend"))
        from onionpi.main import app

        document = app.openapi()

    openapi_path = root / "docs/openapi-v1.json"
    openapi_path.write_text(
        json.dumps(document, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    schemas = document.get("components", {}).get("schemas", {})
    lines = [
        "// Generated by scripts/generate-api-types.py. Do not edit by hand.",
        "",
    ]
    for name, schema in sorted(schemas.items()):
        lines.append(f"export type {name} = {ts_type(schema)}")
        lines.append("")
    generated = root / "frontend/src/generated/api-v1.ts"
    generated.parent.mkdir(parents=True, exist_ok=True)
    generated.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
